vim.api.nvim_set_hl(0, "RainbowDelimiterRed", { fg = "#F28779" })
vim.api.nvim_set_hl(0, "RainbowDelimiterOrange", { fg = "#FFAD66" })
vim.api.nvim_set_hl(0, "RainbowDelimiterYellow", { fg = "#FFFAC2" })
vim.api.nvim_set_hl(0, "RainbowDelimiterGreen", { fg = "#4EC9B0" })
vim.api.nvim_set_hl(0, "RainbowDelimiterCyan", { fg = "#5DE4C7" })
vim.api.nvim_set_hl(0, "RainbowDelimiterBlue", { fg = "#89DDFF" })
vim.api.nvim_set_hl(0, "RainbowDelimiterViolet", { fg = "#D4A1FF" })
